### ISSUE TITLE
First Run Error

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry.tech#252]
When I started the site locally for the first time, this error popped up:

```
MacBookPro:lbry.tech Mark$ npm run watch

> lbry.tech@3.7.0 watch /Users/Mark/WebstormProjects/lbry.tech
> run-p watch:*


> lbry.tech@3.7.0 watch:sass /Users/Mark/WebstormProjects/lbry.tech
> sass --load-path=node_modules --watch app/sass:app/dist --style compressed


> lbry.tech@3.7.0 watch:server /Users/Mark/WebstormProjects/lbry.tech
> NODE_ENV=development nodemon --ignore 'app/dist'

[nodemon] 1.18.10
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
[missing] GitHub token[missing] Redis client URL
— ⚡ 8080
Compiled app/sass/bundle.scss to app/dist/bundle.css.
Sass is watching for changes. Press Ctrl-C to stop.

/Users/Mark/WebstormProjects/lbry.tech/node_modules/sass/sass.dart.js:8362
if(t.a!==0)throw H.a(P.ba("Future already completed"))
           ^

Bad state: Future already completed
    at Object.a (/Users/Mark/WebstormProjects/lbry.tech/node_modules/sass/sass.dart.js:504:3)
    at cH.b8 (/Users/Mark/WebstormProjects/lbry.tech/node_modules/sass/sass.dart.js:8362:20)
    at zM.$0 (/Users/Mark/WebstormProjects/lbry.tech/node_modules/sass/sass.dart.js:15522:8)
    at Object.Gh (/Users/Mark/WebstormProjects/lbry.tech/node_modules/sass/sass.dart.js:464:30)
    at Object.hv (/Users/Mark/WebstormProjects/lbry.tech/node_modules/sass/sass.dart.js:2231:28)
    at Hd (/Users/Mark/WebstormProjects/lbry.tech/node_modules/sass/sass.dart.js:3059:27)
    at FSWatcher.<anonymous> (/Users/Mark/WebstormProjects/lbry.tech/node_modules/sass/sass.dart.js:3048:42)
    at FSWatcher.emit (events.js:188:13)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lbry.tech@3.7.0 watch:sass: `sass --load-path=node_modules --watch app/sass:app/dist --style compressed`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lbry.tech@3.7.0 watch:sass script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Mark/.npm/_logs/2019-02-10T02_48_36_914Z-debug.log
ERROR: "watch:sass" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lbry.tech@3.7.0 watch: `run-p watch:*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lbry.tech@3.7.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Mark/.npm/_logs/2019-02-10T02_48_37_035Z-debug.log
```

When I ran it a second time, there error did not happen.

**Comment by NetOperatorWibby** [comment]
> Future already completed

That...is interesting.

**Comment by NetOperatorWibby** [comment]
I just ran the repo fresh (trying to troubleshoot an issue Jeremy is dealing with) and I had no problems with running it.

It's clearly an issue with the Sass module. Unfortunately, searching for "Future already completed" in the Sass Dart repo returned no results.

Closing for now.
